Repository leonsteinhaeuser/git-tag-bump, pull requests merged in 2025-03, with the labels that each got.

#21 feat: add support to create lightweight tags
  README.md
  main.go
Labels: size/S

#22 chore: update Go version in CI to 1.24.1
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
Labels: size/XS

#26 fix: dirty state during release
  .github/workflows/release.yaml
  go.mod
Labels: size/XS, fix
